version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: personal-website-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    container_name: personal-website-backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=mysql://root:123456@db:3306/personal_website
      - JWT_SECRET=your-jwt-secret-key-change-this
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: personal-website-db
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=personal_website
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

volumes:
  mysql_data: 